import { Item } from "@/Components/Combobox"

export const defaultCompaniesFields: Item[] = [
  { "attribute-name": 'name', name: 'Название' },
  { "attribute-name": 'description', name: 'Описание' },
  { "attribute-name": 'general_phone', name: 'Телефон (основной)' },
  { "attribute-name": 'mobile_phone', name: 'Телефон (мобильный)' },
  { "attribute-name": 'work_phone', name: 'Телефон (рабочий)' },
  { "attribute-name": 'work_phone-postfix', name: 'Добавочный (рабочий)' },
  { "attribute-name": 'other_phone', name: 'Телефон (дополнительный)' },
  { "attribute-name": 'other_phone_postfix', name: 'Добавочный (дополнительный)' },
  { "attribute-name": 'fax', name: 'Факс' },
  { "attribute-name": 'email', name: 'E-mail адрес' },
  { "attribute-name": 'other_email', name: 'E-mail адрес (дополнительный)' },
  { "attribute-name": 'website', name: 'Сайт' },
  { "attribute-name": 'country', name: 'Страна' },
  { "attribute-name": 'region', name: 'Регион' },
  { "attribute-name": 'city', name: 'Город' },
  { "attribute-name": 'address', name: 'Адрес' },
  { "attribute-name": 'zip_code', name: 'Индекс' },
  { "attribute-name": 'actual_country', name: 'Страна' },
  { "attribute-name": 'actual_region', name: 'Область, регион, край' },
  { "attribute-name": 'actual_city', name: 'Город, населенный пункт' },
  { "attribute-name": 'actual_zip-code', name: 'Индекс' },
  { "attribute-name": 'actual_street', name: 'Улица, проспект' },
  { "attribute-name": 'actual_house', name: 'Номер дома' },
  { "attribute-name": 'actual_build', name: 'Корпус' },
  { "attribute-name": 'actual_office', name: 'Номер офиса' },
  { "attribute-name": 'juristic_country', name: 'Юр.адрес Страна' },
  { "attribute-name": 'juristic_region', name: 'Юр.адрес Область, регион, край' },
  { "attribute-name": 'juristic_city', name: 'Юр.адрес Город, населенный пункт' },
  { "attribute-name": 'juristic_zip-code', name: 'Юр.адрес Индекс' },
  { "attribute-name": 'juristic_street', name: 'Юр.адрес Улица, проспект' },
  { "attribute-name": 'juristic_house', name: 'Юр.адрес Номер дома' },
  { "attribute-name": 'juristic_build', name: 'Юр.адрес Корпус' },
  { "attribute-name": 'juristic_office', name: 'Юр.адрес Номер офиса' },
  { "attribute-name": 'mailing_country', name: 'Почта Страна' },
  { "attribute-name": 'mailing_region', name: 'Почта Область, регион, край' },
  { "attribute-name": 'mailing_city', name: 'Почта Город, населенный пункт' },
  { "attribute-name": 'mailing_zip-code', name: 'Почта Индекс' },
  { "attribute-name": 'mailing_street', name: 'Почта Улица, проспект' },
  { "attribute-name": 'mailing_house', name: 'Почта Номер дома' },
  { "attribute-name": 'mailing_build', name: 'Почта Корпус' },
  { "attribute-name": 'mailing_office', name: 'Почта Номер офиса' },
  { "attribute-name": 'full_name', name: 'Полное наименование' },
  { "attribute-name": 'short_name', name: 'Короткое наименование' },
  { "attribute-name": 'inn', name: 'ИНН' },
  { "attribute-name": 'ogrn', name: 'ОГРН' },
  { "attribute-name": 'kpp', name: 'КПП' },
  { "attribute-name": 'okved', name: 'ОКВЭД' },
  { "attribute-name": 'okpo', name: 'ОКПО' },
  { "attribute-name": 'director', name: 'Директор' },
  { "attribute-name": 'accountant', name: 'Бухгалтер' },
  { "attribute-name": 'lawfulness_base', name: 'Правомочность' },
  { "attribute-name": 'manager_name', name: 'ФИО руководителя' },
  { "attribute-name": 'manager_position', name: 'Должность руководителя' },
  { "attribute-name": 'utm_source', name: 'UTM Рекламная система' },
  { "attribute-name": 'utm_medium', name: 'UTM Тип трафика' },
  { "attribute-name": 'utm_campaign', name: 'UTM Название рекламной кампании' },
  { "attribute-name": 'utm_term', name: 'UTM Ключевое слово, которое инициировало показ объявления' },
  { "attribute-name": 'utm_content', name: 'UTM Информация, которая помогает различать объявления, если совпадают другие параметры' },
  { "attribute-name": 'utm_landing-page', name: 'UTM Адрес посадочной страницы' },
  { "attribute-name": 'utm_city', name: 'UTM Город' },
]