import { Item } from "@/Components/Combobox"

export const defaultContactFields: Item[] = [
  { "attribute-name": 'first_name', name: 'Имя' },
  { "attribute-name": 'last_name', name: 'Фамилия' },
  { "attribute-name": 'middle-name', name: 'Отчество' },
  { "attribute-name": 'description', name: 'Описание' },
  { "attribute-name": 'general_phone', name: 'Телефон (основной)' },
  { "attribute-name": 'mobile_phone', name: 'Телефон (мобильный)' },
  { "attribute-name": 'work_phone', name: 'Телефон (рабочий)' },
  { "attribute-name": 'work_phone_postfix', name: 'Добавочный (рабочий)' },
  { "attribute-name": 'other_phone', name: 'Телефон (дополнительный)' },
  { "attribute-name": 'other_phone_postfix', name: 'Добавочный (дополнительный)' },
  { "attribute-name": 'fax', name: 'Факс' },
  { "attribute-name": 'email', name: 'E-mail адрес' },
  { "attribute-name": 'other_email', name: 'E-mail адрес (дополнительный)' },
  { "attribute-name": 'website', name: 'Сайт' },
  { "attribute-name": 'work_country', name: 'Раб. адрес Страна' },
  { "attribute-name": 'work_region', name: 'Раб. адрес Область, регион, край' },
  { "attribute-name": 'work_city', name: 'Раб. адрес Город, населенный пункт' },
  { "attribute-name": 'work_zipcode', name: 'Раб. адрес Индекс' },
  { "attribute-name": 'work_street', name: 'Раб. адрес Улица, проспект' },
  { "attribute-name": 'work_building', name: 'Раб. адрес Номер дома' },
  { "attribute-name": 'work_housing', name: 'Раб. адрес Корпус' },
  { "attribute-name": 'work_apartment', name: 'Раб. адрес Номер офиса или квартиры' },
  { "attribute-name": 'home_country', name: 'Дом.адрес Страна' },
  { "attribute-name": 'home_region', name: 'Дом.адрес Область, регион, край' },
  { "attribute-name": 'home_city', name: 'Дом.адрес Город, населенный пункт' },
  { "attribute-name": 'home_zipcode', name: 'Дом.адрес Индекс' },
  { "attribute-name": 'home_street', name: 'Дом.адрес Улица, проспект' },
  { "attribute-name": 'home_building', name: 'Дом.адрес Номер дома' },
  { "attribute-name": 'home_housing', name: 'Дом.адрес Корпус' },
  { "attribute-name": 'home_apartment', name: 'Дом.адрес Номер офиса или квартиры' },
  { "attribute-name": 'vkontakte', name: 'ВКонтакте' },
  { "attribute-name": 'facebook', name: 'Facebook' },
  { "attribute-name": 'linkedin', name: 'Linked-in' },
  { "attribute-name": 'odnoklassniki', name: 'Одноклассники' },
  { "attribute-name": 'instagram', name: 'Instagram' },
  { "attribute-name": 'twitter', name: 'Twitter' },
  { "attribute-name": 'whatsapp', name: 'WhatsApp' },
  { "attribute-name": 'viber', name: 'Viber' },
  { "attribute-name": 'telegram', name: 'Telegram' },
  { "attribute-name": 'skype', name: 'Skype' },
  { "attribute-name": 'utm_source', name: 'UTM Рекламная система' },
  { "attribute-name": 'utm_medium', name: 'UTM Тип трафика' },
  { "attribute-name": 'utm_campaign', name: 'UTM Название рекламной кампании' },
  { "attribute-name": 'utm_term', name: 'UTM Ключевое слово, которое инициировало показ объявления' },
  { "attribute-name": 'utm_content', name: 'UTM Информация, которая помогает различать объявления, если совпадают другие параметры' },
  { "attribute-name": 'utm_landing-page', name: 'UTM Адрес посадочной страницы' },
  { "attribute-name": 'utm_city', name: 'UTM Город' },
]