import { Item } from "@/Components/Combobox"

export const defaultContactFields: Item[] = [
  { "attribute-name": 'first-name', name: 'Имя' },
  { "attribute-name": 'last-name', name: 'Фамилия' },
  { "attribute-name": 'middle-name', name: 'Отчество' },
  { "attribute-name": 'description', name: 'Описание' },
  { "attribute-name": 'general-phone', name: 'Телефон (основной)' },
  { "attribute-name": 'mobile-phone', name: 'Телефон (мобильный)' },
  { "attribute-name": 'work-phone', name: 'Телефон (рабочий)' },
  { "attribute-name": 'work-phone-postfix', name: 'Добавочный (рабочий)' },
  { "attribute-name": 'other-phone', name: 'Телефон (дополнительный)' },
  { "attribute-name": 'other-phone-postfix', name: 'Добавочный (дополнительный)' },
  { "attribute-name": 'fax', name: 'Факс' },
  { "attribute-name": 'email', name: 'E-mail адрес' },
  { "attribute-name": 'other-email', name: 'E-mail адрес (дополнительный)' },
  { "attribute-name": 'website', name: 'Сайт' },
  { "attribute-name": 'work-country', name: 'Раб. адрес Страна' },
  { "attribute-name": 'work-region', name: 'Раб. адрес Область, регион, край' },
  { "attribute-name": 'work-city', name: 'Раб. адрес Город, населенный пункт' },
  { "attribute-name": 'work-zipcode', name: 'Раб. адрес Индекс' },
  { "attribute-name": 'work-street', name: 'Раб. адрес Улица, проспект' },
  { "attribute-name": 'work-building', name: 'Раб. адрес Номер дома' },
  { "attribute-name": 'work-housing', name: 'Раб. адрес Корпус' },
  { "attribute-name": 'work-apartment', name: 'Раб. адрес Номер офиса или квартиры' },
  { "attribute-name": 'home-country', name: 'Дом.адрес Страна' },
  { "attribute-name": 'home-region', name: 'Дом.адрес Область, регион, край' },
  { "attribute-name": 'home-city', name: 'Дом.адрес Город, населенный пункт' },
  { "attribute-name": 'home-zipcode', name: 'Дом.адрес Индекс' },
  { "attribute-name": 'home-street', name: 'Дом.адрес Улица, проспект' },
  { "attribute-name": 'home-building', name: 'Дом.адрес Номер дома' },
  { "attribute-name": 'home-housing', name: 'Дом.адрес Корпус' },
  { "attribute-name": 'home-apartment', name: 'Дом.адрес Номер офиса или квартиры' },
  { "attribute-name": 'vkontakte', name: 'ВКонтакте' },
  { "attribute-name": 'facebook', name: 'Facebook' },
  { "attribute-name": 'linkedin', name: 'Linked-in' },
  { "attribute-name": 'odnoklassniki', name: 'Одноклассники' },
  { "attribute-name": 'instagram', name: 'Instagram' },
  { "attribute-name": 'twitter', name: 'Twitter' },
  { "attribute-name": 'whatsapp', name: 'WhatsApp' },
  { "attribute-name": 'viber', name: 'Viber' },
  { "attribute-name": 'telegram', name: 'Telegram' },
  { "attribute-name": 'skype', name: 'Skype' },
  { "attribute-name": 'utm-source', name: 'UTM Рекламная система' },
  { "attribute-name": 'utm-medium', name: 'UTM Тип трафика' },
  { "attribute-name": 'utm-campaign', name: 'UTM Название рекламной кампании' },
  { "attribute-name": 'utm-term', name: 'UTM Ключевое слово, которое инициировало показ объявления' },
  { "attribute-name": 'utm-content', name: 'UTM Информация, которая помогает различать объявления, если совпадают другие параметры' },
  { "attribute-name": 'utm-landing-page', name: 'UTM Адрес посадочной страницы' },
  { "attribute-name": 'utm-city', name: 'UTM Город' },
]