import { Item } from "@/Components/Combobox"

export const defaultCompaniesFields: Item[] = [
  { "attribute-name": 'name', name: 'Название' },
  { "attribute-name": 'description', name: 'Описание' },
  { "attribute-name": 'general-phone', name: 'Телефон (основной)' },
  { "attribute-name": 'mobile-phone', name: 'Телефон (мобильный)' },
  { "attribute-name": 'work-phone', name: 'Телефон (рабочий)' },
  { "attribute-name": 'work-phone-postfix', name: 'Добавочный (рабочий)' },
  { "attribute-name": 'other-phone', name: 'Телефон (дополнительный)' },
  { "attribute-name": 'other-phone-postfix', name: 'Добавочный (дополнительный)' },
  { "attribute-name": 'fax', name: 'Факс' },
  { "attribute-name": 'email', name: 'E-mail адрес' },
  { "attribute-name": 'other-email', name: 'E-mail адрес (дополнительный)' },
  { "attribute-name": 'website', name: 'Сайт' },
  { "attribute-name": 'country', name: 'Страна' },
  { "attribute-name": 'region', name: 'Регион' },
  { "attribute-name": 'city', name: 'Город' },
  { "attribute-name": 'address', name: 'Адрес' },
  { "attribute-name": 'zip-code', name: 'Индекс' },
  { "attribute-name": 'actual-country', name: 'Страна' },
  { "attribute-name": 'actual-region', name: 'Область, регион, край' },
  { "attribute-name": 'actual-city', name: 'Город, населенный пункт' },
  { "attribute-name": 'actual-zip-code', name: 'Индекс' },
  { "attribute-name": 'actual-street', name: 'Улица, проспект' },
  { "attribute-name": 'actual-house', name: 'Номер дома' },
  { "attribute-name": 'actual-build', name: 'Корпус' },
  { "attribute-name": 'actual-office', name: 'Номер офиса' },
  { "attribute-name": 'juristic-country', name: 'Юр.адрес Страна' },
  { "attribute-name": 'juristic-region', name: 'Юр.адрес Область, регион, край' },
  { "attribute-name": 'juristic-city', name: 'Юр.адрес Город, населенный пункт' },
  { "attribute-name": 'juristic-zip-code', name: 'Юр.адрес Индекс' },
  { "attribute-name": 'juristic-street', name: 'Юр.адрес Улица, проспект' },
  { "attribute-name": 'juristic-house', name: 'Юр.адрес Номер дома' },
  { "attribute-name": 'juristic-build', name: 'Юр.адрес Корпус' },
  { "attribute-name": 'juristic-office', name: 'Юр.адрес Номер офиса' },
  { "attribute-name": 'mailing-country', name: 'Почта Страна' },
  { "attribute-name": 'mailing-region', name: 'Почта Область, регион, край' },
  { "attribute-name": 'mailing-city', name: 'Почта Город, населенный пункт' },
  { "attribute-name": 'mailing-zip-code', name: 'Почта Индекс' },
  { "attribute-name": 'mailing-street', name: 'Почта Улица, проспект' },
  { "attribute-name": 'mailing-house', name: 'Почта Номер дома' },
  { "attribute-name": 'mailing-build', name: 'Почта Корпус' },
  { "attribute-name": 'mailing-office', name: 'Почта Номер офиса' },
  { "attribute-name": 'full-name', name: 'Полное наименование' },
  { "attribute-name": 'short-name', name: 'Короткое наименование' },
  { "attribute-name": 'inn', name: 'ИНН' },
  { "attribute-name": 'ogrn', name: 'ОГРН' },
  { "attribute-name": 'kpp', name: 'КПП' },
  { "attribute-name": 'okved', name: 'ОКВЭД' },
  { "attribute-name": 'okpo', name: 'ОКПО' },
  { "attribute-name": 'director', name: 'Директор' },
  { "attribute-name": 'accountant', name: 'Бухгалтер' },
  { "attribute-name": 'lawfulness-base', name: 'Правомочность' },
  { "attribute-name": 'manager-name', name: 'ФИО руководителя' },
  { "attribute-name": 'manager-position', name: 'Должность руководителя' },
  { "attribute-name": 'utm-source', name: 'UTM Рекламная система' },
  { "attribute-name": 'utm-medium', name: 'UTM Тип трафика' },
  { "attribute-name": 'utm-campaign', name: 'UTM Название рекламной кампании' },
  { "attribute-name": 'utm-term', name: 'UTM Ключевое слово, которое инициировало показ объявления' },
  { "attribute-name": 'utm-content', name: 'UTM Информация, которая помогает различать объявления, если совпадают другие параметры' },
  { "attribute-name": 'utm-landing-page', name: 'UTM Адрес посадочной страницы' },
  { "attribute-name": 'utm-city', name: 'UTM Город' },
]