import { Item } from "@/Components/Combobox"

export const yandexGroupFields: Item[] = [
  { "attribute-name": "ym:s:firstTrafficSource", name: "Источник трафика" },
  { "attribute-name": "ym:s:firstSourceEngine", name: "Источник трафика (детально)" },
  { "attribute-name": "ym:s:firstAdvEngine", name: "Рекламная система" },
  { "attribute-name": "ym:s:firstReferalSource", name: "Переход с сайтов" },
  { "attribute-name": "ym:s:firstMessenger", name: "Переход из мессенджера" },
  { "attribute-name": "ym:s:firstRecommendationSystem", name: "Переход из рекомендательной системы" },
  { "attribute-name": "ym:s:firstQRCodeProvider", name: "QR-код провайдер" },
  { "attribute-name": "ym:s:firstDirectClickOrder", name: "Кампания Яндекс.Директа" },
  { "attribute-name": "ym:s:firstDirectBannerGroup", name: "Группа объявлений" },
  { "attribute-name": "ym:s:firstDirectClickBanner", name: "Объявление Яндекс.Директа" },
  { "attribute-name": "ym:s:firstDirectPhraseOrCond", name: "Условие показа объявления" },
  { "attribute-name": "ym:s:firstDirectPlatformType", name: "Тип площадки" },
  { "attribute-name": "ym:s:firstDirectPlatform", name: "Площадка" },
  { "attribute-name": "ym:s:firstDirectSearchPhrase", name: "Поисковая фраза (Директ)" },
  { "attribute-name": "ym:s:firstDirectConditionType", name: "Тип условия показа объявления" },
  { "attribute-name": "ym:s:firstCurrency", name: "Валюта" },
  { "attribute-name": "ym:s:firstDisplayCampaign", name: "Номер заказа Яндекс.Дисплея" },
  { "attribute-name": "ym:s:marketSearchPhrase", name: "Фраза (Маркет)" },
  { "attribute-name": "ym:s:firstSearchEngineRoot", name: "Поисковая система" },
  { "attribute-name": "ym:s:firstSearchEngine", name: "Поисковая система (детально)" },
  { "attribute-name": "ym:s:firstSearchPhrase", name: "Поисковая фраза" },
  { "attribute-name": "ym:s:firstSocialNetwork", name: "Cоциальная сеть" },
  { "attribute-name": "ym:s:firstSocialNetworkProfile", name: "Группа соц. сети" },
  { "attribute-name": "ym:s:referer", name: "Реферер" },
  { "attribute-name": "ym:s:refererProto", name: "Протокол реферера" },
  { "attribute-name": "ym:s:refererDomain", name: "Домен реферера" },
  { "attribute-name": "ym:s:refererPathFull", name: "Путь (полный) реферера" },
  { "attribute-name": "ym:s:refererPath", name: "Путь реферера" },
  { "attribute-name": "ym:s:refererPathLevel1", name: "Реферер, ур. 1" },
  { "attribute-name": "ym:s:refererPathLevel2", name: "Реферер, ур. 2" },
  { "attribute-name": "ym:s:refererPathLevel3", name: "Реферер, ур. 3" },
  { "attribute-name": "ym:s:refererPathLevel4", name: "Реферер, ур. 4" },
  { "attribute-name": "ym:s:refererPathLevel5", name: "Реферер, ур. 5" },
  { "attribute-name": "ym:s:externalReferer", name: "Внешний реферер" },
  { "attribute-name": "ym:s:externalRefererProto", name: "Протокол внешнего реферера" },
  { "attribute-name": "ym:s:externalRefererDomain", name: "Домен внешнего реферера" },
  { "attribute-name": "ym:s:externalRefererPathFull", name: "Путь (полный) внешнего реферера" },
  { "attribute-name": "ym:s:externalRefererPath", name: "Путь внешнего реферера" },
  { "attribute-name": "ym:s:externalRefererPathLevel1", name: "Внешний реферер, ур. 1" },
  { "attribute-name": "ym:s:externalRefererPathLevel2", name: "Внешний реферер, ур. 2" },
  { "attribute-name": "ym:s:externalRefererPathLevel3", name: "Внешний реферер, ур. 3" },
  { "attribute-name": "ym:s:externalRefererPathLevel4", name: "Внешний реферер, ур. 4" },
  { "attribute-name": "ym:s:externalRefererPathLevel5", name: "Внешний реферер, ур. 5" },
  { "attribute-name": "ym:s:firstFrom", name: "Метка from" },
  { "attribute-name": "ym:s:firstUTMCampaign", name: "UTM Campaign" },
  { "attribute-name": "ym:s:firstUTMContent", name: "UTM Content" },
  { "attribute-name": "ym:s:firstUTMMedium", name: "UTM Medium" },
  { "attribute-name": "ym:s:firstUTMSource", name: "UTM Source" },
  { "attribute-name": "ym:s:firstUTMTerm", name: "UTM Term" },
  { "attribute-name": "ym:s:firstOpenstatAd", name: "Openstat Ad" },
  { "attribute-name": "ym:s:firstOpenstatCampaign", name: "Openstat Campaign" },
  { "attribute-name": "ym:s:firstOpenstatService", name: "Openstat Service" },
  { "attribute-name": "ym:s:firstOpenstatSource", name: "Openstat Source" },
  { "attribute-name": "ym:s:firstHasGCLID", name: "Наличие GCLID" },
  { "attribute-name": "ym:s:goal", name: "Достигнутая цель" },
  { "attribute-name": "ym:s:pageViewsInterval", name: "Глубина просмотра" },
  { "attribute-name": "ym:s:pageViews", name: "Глубина просмотра (детально)" },
  { "attribute-name": "ym:s:visitDurationInterval", name: "Время на сайте" },
  { "attribute-name": "ym:s:visitDuration", name: "Время на сайте (детально)" },
  { "attribute-name": "ym:s:bounce", name: "Отказность" },
  { "attribute-name": "ym:s:isRobot", name: "Роботность" },
  { "attribute-name": "ym:s:isTurboPage", name: "Турбо-страница" },
  { "attribute-name": "ym:s:counterID", name: "Счетчик" },
  { "attribute-name": "ym:s:startURL", name: "Страница входа" },
  { "attribute-name": "ym:s:startURLProto", name: "Протокол страницы входа" },
  { "attribute-name": "ym:s:topLevelDomain", name: "Домен верхнего уровня страницы входа" },
  { "attribute-name": "ym:s:startURLDomain", name: "Домен страницы входа" },
  { "attribute-name": "ym:s:startURLPathFull", name: "Путь (полный) страницы входа" },
  { "attribute-name": "ym:s:startURLPath", name: "Путь страницы входа" },
  { "attribute-name": "ym:s:startURLPathLevel1", name: "Страница входа, ур. 1" },
  { "attribute-name": "ym:s:startURLPathLevel2", name: "Страница входа, ур. 2" },
  { "attribute-name": "ym:s:startURLPathLevel3", name: "Страница входа, ур. 3" },
  { "attribute-name": "ym:s:startURLPathLevel4", name: "Страница входа, ур. 4" },
  { "attribute-name": "ym:s:startURLPathLevel5", name: "Страница входа, ур. 5" },
  { "attribute-name": "ym:s:endURL", name: "Страница выхода" },
  { "attribute-name": "ym:s:endURLProto", name: "Протокол страницы выхода" },
  { "attribute-name": "ym:s:endURLDomain", name: "Домен страницы выхода" },
  { "attribute-name": "ym:s:endURLPathFull", name: "Путь (полный) страницы выхода" },
  { "attribute-name": "ym:s:endURLPath", name: "Путь страницы выхода" },
  { "attribute-name": "ym:s:endURLPathLevel1", name: "Страница выхода, ур. 1" },
  { "attribute-name": "ym:s:endURLPathLevel2", name: "Страница выхода, ур. 2" },
  { "attribute-name": "ym:s:endURLPathLevel3", name: "Страница выхода, ур. 3" },
  { "attribute-name": "ym:s:endURLPathLevel4", name: "Страница выхода, ур. 4" },
  { "attribute-name": "ym:s:endURLPathLevel5", name: "Страница выхода, ур. 5" },
  { "attribute-name": "ym:s:paramsLevel1", name: "Параметр визита, ур. 1" },
  { "attribute-name": "ym:s:paramsLevel2", name: "Параметр визита, ур. 2" },
  { "attribute-name": "ym:s:paramsLevel3", name: "Параметр визита, ур. 3" },
  { "attribute-name": "ym:s:paramsLevel4", name: "Параметр визита, ур. 4" },
  { "attribute-name": "ym:s:paramsLevel5", name: "Параметр визита, ур. 5" },
  { "attribute-name": "ym:s:paramsLevel6", name: "Параметр визита, ур. 6" },
  { "attribute-name": "ym:s:paramsLevel7", name: "Параметр визита, ур. 7" },
  { "attribute-name": "ym:s:paramsLevel8", name: "Параметр визита, ур. 8" },
  { "attribute-name": "ym:s:paramsLevel9", name: "Параметр визита, ур. 9" },
  { "attribute-name": "ym:s:paramsLevel10", name: "Параметр визита, ур. 10" },
  { "attribute-name": "ym:s:date", name: "Дата визита" },
  { "attribute-name": "ym:s:datePeriod<group>", name: "Интервал дат визита" },
  { "attribute-name": "ym:s:startOfYear", name: "Год визита" },
  { "attribute-name": "ym:s:startOfQuarter", name: "Квартал визита" },
  { "attribute-name": "ym:s:startOfMonth", name: "Месяц визита" },
  { "attribute-name": "ym:s:startOfWeek", name: "Неделя визита" },
  { "attribute-name": "ym:s:startOfHour", name: "Час визита" },
  { "attribute-name": "ym:s:startOfDekaminute", name: "Начало декаминуты визита" },
  { "attribute-name": "ym:s:startOfMinute", name: "Минута визита" },
  { "attribute-name": "ym:s:dateTime", name: "Дата и время визита" },
  { "attribute-name": "ym:s:year", name: "Год визита" },
  { "attribute-name": "ym:s:month", name: "Месяц визита" },
  { "attribute-name": "ym:s:dayOfMonth", name: "День месяца визита" },
  { "attribute-name": "ym:s:dayOfWeek", name: "День недели визита" },
  { "attribute-name": "ym:s:hour", name: "Час визита" },
  { "attribute-name": "ym:s:minute", name: "Минута визита" },
  { "attribute-name": "ym:s:dekaminute", name: "Декаминута визита" },
  { "attribute-name": "ym:s:hourMinute", name: "Час и минута визита" },
  { "attribute-name": "ym:s:isNewUser", name: "Является ли визит первым визитом посетителя" },
  { "attribute-name": "ym:s:userVisitsInterval", name: "Визитов в истории" },
  { "attribute-name": "ym:s:userVisits", name: "Всего визитов" },
  { "attribute-name": "ym:s:daysSinceFirstVisitInterval", name: "Дней от первого визита" },
  { "attribute-name": "ym:s:daysSinceFirstVisit", name: "Дней от первого визита (детально)" },
  { "attribute-name": "ym:s:daysSincePreviousVisitInterval", name: "Время возврата" },
  { "attribute-name": "ym:s:daysSincePreviousVisit", name: "Время с предыдущего визита" },
  { "attribute-name": "ym:s:userVisitsPeriodInterval", name: "Периодичность" },
  { "attribute-name": "ym:s:userVisitsPeriod", name: "Периодичность (детально)" },
  { "attribute-name": "ym:s:firstVisitDate", name: "Дата первого визита" },
  { "attribute-name": "ym:s:firstVisitDatePeriod<group>", name: "Дата первого визита (интервал)" },
  { "attribute-name": "ym:s:firstVisitStartOfYear", name: "Год первого визита" },
  { "attribute-name": "ym:s:firstVisitStartOfQuarter", name: "Квартал первого визита" },
  { "attribute-name": "ym:s:firstVisitStartOfMonth", name: "Месяц первого визита" },
  { "attribute-name": "ym:s:firstVisitStartOfWeek", name: "Неделя первого визита" },
  { "attribute-name": "ym:s:firstVisitStartOfHour", name: "Час первого визита" },
  { "attribute-name": "ym:s:firstVisitStartOfDekaminute", name: "Начало декаминуты первого визита" },
  { "attribute-name": "ym:s:firstVisitStartOfMinute", name: "Минута первого визита" },
  { "attribute-name": "ym:s:firstVisitDateTime", name: "Дата и время первого визита" },
  { "attribute-name": "ym:s:firstVisitYear", name: "Год первого визита" },
  { "attribute-name": "ym:s:firstVisitMonth", name: "Месяц первого визита" },
  { "attribute-name": "ym:s:firstVisitDayOfMonth", name: "День месяца первого визита" },
  { "attribute-name": "ym:s:firstVisitDayOfWeek", name: "День недели первого визита посетителя" },
  { "attribute-name": "ym:s:firstVisitHour", name: "Час первого визита" },
  { "attribute-name": "ym:s:firstVisitMinute", name: "Минута первого визита" },
  { "attribute-name": "ym:s:firstVisitDekaminute", name: "Декаминута первого визита" },
  { "attribute-name": "ym:s:firstVisitHourMinute", name: "Час и минута первого визита" },
  { "attribute-name": "ym:s:previousVisitDate", name: "Дата предыдущего визита" },
  { "attribute-name": "ym:s:previousVisitDatePeriod<group>", name: "Дата предыдущего визита (интервал)" },
  { "attribute-name": "ym:s:previousVisitStartOfYear", name: "Год предпоследнего визита" },
  { "attribute-name": "ym:s:previousVisitStartOfQuarter", name: "Квартал предпоследнего визита" },
  { "attribute-name": "ym:s:previousVisitYear", name: "Год предыдущего визита" },
  { "attribute-name": "ym:s:previousVisitMonth", name: "Месяц предыдущего визита" },
  { "attribute-name": "ym:s:previousVisitDayOfMonth", name: "День месяца предыдущего визита" },
  { "attribute-name": "ym:s:previousVisitDayOfWeek", name: "День недели предыдущего визита" },
  { "attribute-name": "ym:s:gender", name: "Пол" },
  { "attribute-name": "ym:s:ageInterval", name: "Возраст" },
  { "attribute-name": "ym:s:interest", name: "Категория интересов" },
  { "attribute-name": "ym:s:interest2d1", name: "Категория интересов, ур. 1" },
  { "attribute-name": "ym:s:interest2d2", name: "Категория интересов, ур. 2" },
  { "attribute-name": "ym:s:interest2d3", name: "Категория интересов, ур. 3" },
  { "attribute-name": "ym:s:clientID", name: "ClientID" },
  { "attribute-name": "ym:s:regionContinent", name: "Континент" },
  { "attribute-name": "ym:s:regionCountry", name: "Страна" },
  { "attribute-name": "ym:s:regionDistrict", name: "Округ" },
  { "attribute-name": "ym:s:regionArea", name: "Область" },
  { "attribute-name": "ym:s:regionCity", name: "Город" },
  { "attribute-name": "ym:s:regionCitySize", name: "Размер города" },
  { "attribute-name": "ym:s:browserLanguage", name: "Язык браузера" },
  { "attribute-name": "ym:s:browserCountry", name: "Страна браузера" },
  { "attribute-name": "ym:s:clientTimeZone", name: "Часовой пояс на компьютере посетителя" },
  { "attribute-name": "ym:s:ipAddress", name: "IP-адрес" },
  { "attribute-name": "ym:s:deviceCategory", name: "Тип устройства" },
  { "attribute-name": "ym:s:mobilePhone", name: "Производитель устройства" },
  { "attribute-name": "ym:s:mobilePhoneModel", name: "Модель устройства" },
  { "attribute-name": "ym:s:operatingSystemRoot", name: "Группа операционных систем" },
  { "attribute-name": "ym:s:operatingSystem", name: "Операционная система (детально)" },
  { "attribute-name": "ym:s:browser", name: "Браузер" },
  { "attribute-name": "ym:s:browserAndVersionMajor", name: "Версия браузера" },
  { "attribute-name": "ym:s:browserAndVersion", name: "Полная версия браузера" },
  { "attribute-name": "ym:s:cookieEnabled", name: "Наличие Cookie" },
  { "attribute-name": "ym:s:javascriptEnabled", name: "Наличие Javascript" },
  { "attribute-name": "ym:s:hasAdBlocker", name: "Наличие блокировщиков рекламы" },
  { "attribute-name": "ym:s:browserEngine", name: "Движок браузера" },
  { "attribute-name": "ym:s:browserEngineVersion1", name: "Major-версия движка браузера" },
  { "attribute-name": "ym:s:browserEngineVersion2", name: "Minor-версия движка браузера" },
  { "attribute-name": "ym:s:browserEngineVersion3", name: "Build-версия движка браузера" },
  { "attribute-name": "ym:s:browserEngineVersion4", name: "Revision-версия движка браузера" },
  { "attribute-name": "ym:s:screenFormat", name: "Соотношение сторон" },
  { "attribute-name": "ym:s:screenColors", name: "Глубина цвета" },
  { "attribute-name": "ym:s:screenOrientation", name: "Ориентация экрана" },
  { "attribute-name": "ym:s:screenResolution", name: "Разрешение" },
  { "attribute-name": "ym:s:screenWidth", name: "Логическая ширина" },
  { "attribute-name": "ym:s:screenHeight", name: "Логическая высота" },
  { "attribute-name": "ym:s:physicalScreenResolution", name: "Реальное разрешение" },
  { "attribute-name": "ym:s:physicalScreenWidth", name: "Физическая ширина" },
  { "attribute-name": "ym:s:physicalScreenHeight", name: "Физическая высота" },
  { "attribute-name": "ym:s:windowClientArea", name: "Размер окна" },
  { "attribute-name": "ym:s:windowClientWidth", name: "Ширина окна" },
  { "attribute-name": "ym:s:windowClientHeight", name: "Высота окна" },
  { "attribute-name": "ym:s:productID", name: "ID товара" },
  { "attribute-name": "ym:s:productName", name: "Название товара" },
  { "attribute-name": "ym:s:productBrand", name: "Бренд" },
  { "attribute-name": "ym:s:productVariant", name: "Вариант товара" },
  { "attribute-name": "ym:s:productPosition", name: "Позиция товара" },
  { "attribute-name": "ym:s:productPrice", name: "Стоимость единицы товара" },
  { "attribute-name": "ym:s:productSum", name: "Стоимость товара" },
  { "attribute-name": "ym:s:productCurrency", name: "Валюта" },
  { "attribute-name": "ym:s:purchaseID", name: "ID покупки" },
  { "attribute-name": "ym:s:purchaseCoupon", name: "Промокод покупки" },
  { "attribute-name": "ym:s:purchaseRevenue", name: "Доход от покупки" },
  { "attribute-name": "ym:s:productCategoryLevel1", name: "Категория товара, ур. 1" },
  { "attribute-name": "ym:s:productCategoryLevel2", name: "Категория товара, ур. 2" },
  { "attribute-name": "ym:s:productCategoryLevel3", name: "Категория товара, ур. 3" },
  { "attribute-name": "ym:s:productCategoryLevel4", name: "Категория товара, ур. 4" },
  { "attribute-name": "ym:s:productCategoryLevel5", name: "Категория товара, ур. 5" },
  { "attribute-name": "ym:s:productCoupon", name: "Промокод товара" },
  { "attribute-name": "ym:s:productIDCart", name: "ID товара в корзине" },
  { "attribute-name": "ym:s:productNameCart", name: "Название товара в корзине" },
  { "attribute-name": "ym:s:productBrandCart", name: "Бренд товара в корзине" },
  { "attribute-name": "ym:s:PProductID", name: "ID товара в заказе" },
  { "attribute-name": "ym:s:PProductName", name: "Название товара в заказе" },
  { "attribute-name": "ym:s:PProductBrand", name: "Бренд товара в заказе" },
  { "attribute-name": "ym:s:purchaseExistsVisit", name: "Наличие покупок в визите" },
  { "attribute-name": "ym:s:purchaseRevenueVisit", name: "Сумма покупок в визите" },
  { "attribute-name": "ym:s:offlineCallTag", name: "Метка" },
  { "attribute-name": "ym:s:offlineCallMissed", name: "Пропущенный / Отвеченный" },
  { "attribute-name": "ym:s:offlineCallFirstTimeCaller", name: "Первичный / Повторный" },
  { "attribute-name": "ym:s:offlineCallHoldDuration", name: "Время ожидания" },
  { "attribute-name": "ym:s:offlineCallTalkDuration", name: "Время разговора" },
  { "attribute-name": "ym:s:yanPageID", name: "Рекламная площадка" },
  { "attribute-name": "ym:s:yanBlockID", name: "Рекламный блок" },
  { "attribute-name": "ym:s:yanBlockSize", name: "Размер блока" },
  { "attribute-name": "ym:s:yanUrl", name: "Страница с рекламными событиями" },
  { "attribute-name": "ym:s:yanUrlPathLevel1", name: "Страница с рекламными событиями, ур.1" },
  { "attribute-name": "ym:s:yanUrlPathLevel2", name: "Страница с рекламными событиями, ур.2" },
  { "attribute-name": "ym:s:yanUrlPathLevel3", name: "Страница с рекламными событиями, ур.3" },
  { "attribute-name": "ym:s:yanUrlPathLevel4", name: "Страница с рекламными событиями, ур.4" },
  { "attribute-name": "ym:s:adfoxSite", name: "Сайт" },
  { "attribute-name": "ym:s:adfoxSection", name: "Раздел" },
  { "attribute-name": "ym:s:adfoxPlace", name: "Площадка" },
  { "attribute-name": "ym:s:adfoxBanner", name: "Баннер" },
  { "attribute-name": "ym:s:adfoxBannerType", name: "Тип баннера" },
  { "attribute-name": "ym:s:adfoxCampaign", name: "Кампания" },
  { "attribute-name": "ym:s:adfoxOwner", name: "Владелец" },
  { "attribute-name": "ym:s:adfoxYanPage", name: "РСЯ page Id" },
  { "attribute-name": "ym:s:adfoxYanImp", name: "РСЯ block Id" },
  { "attribute-name": "ym:s:adfoxHeaderBidding", name: "Монетизатор Header bidding" },
  { "attribute-name": "ym:s:adfoxLevel1", name: "Тип монетизации" },
  { "attribute-name": "ym:s:adfoxLevel2", name: "Монетизатор" },
  { "attribute-name": "ym:s:adfoxLevel1Chained", name: "Adfox, ур.1" },
  { "attribute-name": "ym:s:adfoxLevel2Chained", name: "Adfox, ур.2" },
  { "attribute-name": "ym:s:adfoxLevel3Chained", name: "Adfox, ур.3" },
  { "attribute-name": "ym:s:adfoxLevel4Chained", name: "Adfox, ур.4" },
  { "attribute-name": "ym:s:adfoxUrlPathLevel1", name: "Страница с рекламными событиями Adfox, ур.1" },
  { "attribute-name": "ym:s:adfoxUrlPathLevel2", name: "Страница с рекламными событиями Adfox, ур.2" },
  { "attribute-name": "ym:s:adfoxUrlPathLevel3", name: "Страница с рекламными событиями Adfox, ур.3" },
  { "attribute-name": "ym:s:adfoxUrlPathLevel4", name: "Страница с рекламными событиями Adfox, ур.4" },
  { "attribute-name": "ym:s:adfoxPuidKey", name: "Параметр рекламной кампании (puid)" },
  { "attribute-name": "ym:s:adfoxPuidValue", name: "Значение параметра рекламной кампании" },
  { "attribute-name": "ym:s:publisherArticleTitle", name: "Заголовок материала" },
  { "attribute-name": "ym:s:publisherArticleRubric", name: "Рубрика, ур. 1" },
  { "attribute-name": "ym:s:publisherArticleRubric2", name: "Рубрика, ур. 2" },
  { "attribute-name": "ym:s:publisherArticlePublishedDate", name: "Опубликовано" },
  { "attribute-name": "ym:s:publisherArticleURL", name: "URL материала" },
  { "attribute-name": "ym:s:publisherArticleScrollDown", name: "Глубина скролла материалов" },
  { "attribute-name": "ym:s:publisherArticleHasFullScroll", name: "Доскроллы" },
  { "attribute-name": "ym:s:publisherArticleReadPart", name: "Глубина дочтения материалов" },
  { "attribute-name": "ym:s:publisherArticleHasFullRead", name: "Дочтения" },
  { "attribute-name": "ym:s:publisherArticleFromTitle", name: "Заголовок материала-реферера" },
  { "attribute-name": "ym:s:publisherArticleHasRecircled", name: "Наличие перехода с материала" },
  { "attribute-name": "ym:s:publisherArticleAuthor", name: "Автор" },
  { "attribute-name": "ym:s:publisherArticleTopic", name: "Тематика" },
  { "attribute-name": "ym:s:publisherLongArticle", name: "Длина материала" },
  { "attribute-name": "ym:s:publisherTrafficSource", name: "Источник переходов" },
  { "attribute-name": "ym:s:publisherTrafficSource2", name: "Источник переходов (детально)" },
  { "attribute-name": "ym:s:publisherPageFormat", name: "Формат страницы" },
  { "attribute-name": "ym:s:vacuumSurface", name: "Сервис Яндекса" },
  { "attribute-name": "ym:s:vacuumEvent", name: "Целевое событие" },
  { "attribute-name": "ym:s:vacuumOrganization", name: "Организация" },
  { "attribute-name": "ym:pv:title", name: "Заголовок страницы" },
  { "attribute-name": "ym:pv:URL", name: "Адрес страницы" },
  { "attribute-name": "ym:pv:URLProto", name: "Протокол страницы" },
  { "attribute-name": "ym:pv:URLDomain", name: "Домен страницы" },
  { "attribute-name": "ym:pv:URLPathFull", name: "Путь (полный) страницы" },
  { "attribute-name": "ym:pv:URLPath", name: "Путь страницы" },
  { "attribute-name": "ym:pv:URLPathLevel1", name: "Адрес, ур. 1" },
  { "attribute-name": "ym:pv:URLPathLevel2", name: "Адрес, ур. 2" },
  { "attribute-name": "ym:pv:URLPathLevel3", name: "Адрес, ур. 3" },
  { "attribute-name": "ym:pv:URLPathLevel4", name: "Адрес, ур. 4" },
  { "attribute-name": "ym:pv:URLPathLevel5", name: "Адрес, ур. 5" },
  { "attribute-name": "ym:pv:URLParamName", name: "Параметр URL" },
  { "attribute-name": "ym:pv:URLParamNameAndValue", name: "Значение параметра URL" },
  { "attribute-name": "ym:pv:referer", name: "Реферер" },
  { "attribute-name": "ym:pv:refererProto", name: "Протокол реферера" },
  { "attribute-name": "ym:pv:refererDomain", name: "Домен реферера" },
  { "attribute-name": "ym:pv:refererPathFull", name: "Путь (полный) реферера" },
  { "attribute-name": "ym:pv:refererPath", name: "Путь реферера" },
  { "attribute-name": "ym:pv:refererPathLevel1", name: "Реферер, ур. 1" },
  { "attribute-name": "ym:pv:refererPathLevel2", name: "Реферер, ур. 2" },
  { "attribute-name": "ym:pv:refererPathLevel3", name: "Реферер, ур. 3" },
  { "attribute-name": "ym:pv:refererPathLevel4", name: "Реферер, ур. 4" },
  { "attribute-name": "ym:pv:refererPathLevel5", name: "Реферер, ур. 5" },
  { "attribute-name": "ym:pv:from", name: "Метка from" },
  { "attribute-name": "ym:pv:UTMCampaign", name: "UTM Campaign" },
  { "attribute-name": "ym:pv:UTMContent", name: "UTM Content" },
  { "attribute-name": "ym:pv:UTMMedium", name: "UTM Medium" },
  { "attribute-name": "ym:pv:UTMSource", name: "UTM Source" },
  { "attribute-name": "ym:pv:UTMTerm", name: "UTM Term" },
  { "attribute-name": "ym:pv:openstatAd", name: "Openstat Ad" },
  { "attribute-name": "ym:pv:openstatCampaign", name: "Openstat Campaign" },
  { "attribute-name": "ym:pv:openstatService", name: "Openstat Service" },
  { "attribute-name": "ym:pv:openstatSource", name: "Openstat Source" },
  { "attribute-name": "ym:pv:hasGCLID", name: "Наличие GCLID" },
  { "attribute-name": "ym:pv:date", name: "Дата просмотра" },
  { "attribute-name": "ym:pv:datePeriod<group>", name: "Дата" },
  { "attribute-name": "ym:pv:startOfYear", name: "Год просмотра" },
  { "attribute-name": "ym:pv:startOfQuarter", name: "Квартал просмотра" },
  { "attribute-name": "ym:pv:startOfMonth", name: "Месяц просмотра" },
  { "attribute-name": "ym:pv:startOfWeek", name: "Неделя просмотра" },
  { "attribute-name": "ym:pv:startOfHour", name: "Час просмотра" },
  { "attribute-name": "ym:pv:startOfDekaminute", name: "Начало декаминуты просмотра" },
  { "attribute-name": "ym:pv:startOfMinute", name: "Минута просмотра" },
  { "attribute-name": "ym:pv:dateTime", name: "Дата и время просмотра" },
  { "attribute-name": "ym:pv:year", name: "Год просмотра" },
  { "attribute-name": "ym:pv:month", name: "Месяц просмотра" },
  { "attribute-name": "ym:pv:dayOfMonth", name: "День месяца просмотра" },
  { "attribute-name": "ym:pv:dayOfWeek", name: "День недели просмотра" },
  { "attribute-name": "ym:pv:hour", name: "Час просмотра в формате HH:00" },
  { "attribute-name": "ym:pv:minute", name: "Минута просмотра" },
  { "attribute-name": "ym:pv:dekaminute", name: "Декаминута просмотра" },
  { "attribute-name": "ym:pv:hourMinute", name: "Час и минута просмотра" },
  { "attribute-name": "ym:pv:gender", name: "Пол" },
  { "attribute-name": "ym:pv:ageInterval", name: "Возраст" },
  { "attribute-name": "ym:pv:regionContinent", name: "Континент" },
  { "attribute-name": "ym:pv:regionCountry", name: "Страна" },
  { "attribute-name": "ym:pv:regionDistrict", name: "Округ" },
  { "attribute-name": "ym:pv:regionArea", name: "Область" },
  { "attribute-name": "ym:pv:regionCity", name: "Город" },
  { "attribute-name": "ym:pv:regionCitySize", name: "Размер города" },
  { "attribute-name": "ym:pv:browserLanguage", name: "Язык браузера" },
  { "attribute-name": "ym:pv:browserCountry", name: "Страна браузера" },
  { "attribute-name": "ym:pv:clientTimeZone", name: "Часовой пояс на компьютере посетителя" },
  { "attribute-name": "ym:pv:ipAddress", name: "IP-адрес" },
  { "attribute-name": "ym:pv:deviceCategory", name: "Тип устройства" },
  { "attribute-name": "ym:pv:mobilePhone", name: "Производитель устройства" },
  { "attribute-name": "ym:pv:mobilePhoneModel", name: "Модель устройства" },
  { "attribute-name": "ym:pv:operatingSystemRoot", name: "Группа операционных систем" },
  { "attribute-name": "ym:pv:operatingSystem", name: "Операционная система (детально)" },
  { "attribute-name": "ym:pv:browser", name: "Браузер" },
  { "attribute-name": "ym:pv:browserAndVersionMajor", name: "Версия браузера" },
  { "attribute-name": "ym:pv:browserAndVersion", name: "Полная версия браузера" },
  { "attribute-name": "ym:pv:cookieEnabled", name: "Наличие Cookie" },
  { "attribute-name": "ym:pv:javascriptEnabled", name: "Наличие Javascript" },
  { "attribute-name": "ym:pv:hasAdBlocker", name: "Наличие блокировщиков рекламы" },
  { "attribute-name": "ym:pv:browserEngine", name: "Движок браузера" },
  { "attribute-name": "ym:pv:browserEngineVersion1", name: "Major-версия движка браузера" },
  { "attribute-name": "ym:pv:browserEngineVersion2", name: "Minor-версия движка браузера" },
  { "attribute-name": "ym:pv:browserEngineVersion3", name: "Build-версия движка браузера" },
  { "attribute-name": "ym:pv:browserEngineVersion4", name: "Revision-версия движка браузера" },
  { "attribute-name": "ym:pv:screenFormat", name: "Соотношение сторон" },
  { "attribute-name": "ym:pv:screenColors", name: "Глубина цвета" },
  { "attribute-name": "ym:pv:screenOrientation", name: "Ориентация экрана" },
  { "attribute-name": "ym:pv:screenResolution", name: "Разрешение" },
  { "attribute-name": "ym:pv:screenWidth", name: "Логическая ширина" },
  { "attribute-name": "ym:pv:screenHeight", name: "Логическая высота" },
  { "attribute-name": "ym:pv:physicalScreenResolution", name: "Реальное разрешение" },
  { "attribute-name": "ym:pv:physicalScreenWidth", name: "Физическая ширина" },
  { "attribute-name": "ym:pv:physicalScreenHeight", name: "Физическая высота" },
  { "attribute-name": "ym:pv:windowClientArea", name: "Размер окна" },
  { "attribute-name": "ym:pv:windowClientWidth", name: "Ширина окна" },
  { "attribute-name": "ym:pv:windowClientHeight", name: "Высота окна" },
  { "attribute-name": "ym:ad:firstDirectOrder", name: "Кампания Яндекс.Директа" },
  { "attribute-name": "ym:ad:firstDirectBannerGroup", name: "Группа объявлений" },
  { "attribute-name": "ym:ad:firstDirectBanner", name: "Объявление Яндекс.Директа" },
  { "attribute-name": "ym:ad:firstDirectPhraseOrCond", name: "Условие показа объявления" },
  { "attribute-name": "ym:ad:firstDirectPlatformType", name: "Тип площадки" },
  { "attribute-name": "ym:ad:firstDirectPlatform", name: "Площадка" },
  { "attribute-name": "ym:ad:firstDirectSearchPhrase", name: "Поисковая фраза (Директ)" },
  { "attribute-name": "ym:ad:firstDirectConditionType", name: "Тип условия показа объявления" },
  { "attribute-name": "ym:ad:firstCurrency", name: "Валюта" },
  { "attribute-name": "ym:ad:firstDisplayCampaign", name: "Номер заказа Яндекс.Дисплея" },
  { "attribute-name": "ym:up:paramsLevel1", name: "Параметр посетителя, ур 1" },
  { "attribute-name": "ym:up:paramsLevel2", name: "Параметр посетителя, ур 2" },
  { "attribute-name": "ym:up:paramsLevel3", name: "Параметр посетителя, ур 3" },
  { "attribute-name": "ym:up:paramsLevel4", name: "Параметр посетителя, ур 4" },
  { "attribute-name": "ym:up:paramsLevel5", name: "Параметр посетителя, ур 5" },
  { "attribute-name": "ym:ev:firstExpenseSource", name: "Рекламный канал" },
  { "attribute-name": "ym:ev:firstExpenseMedium", name: "Тип рекламного канала" },
  { "attribute-name": "ym:ev:firstExpenseCampaign", name: "Кампания" },
  { "attribute-name": "ym:ev:firstExpenseTerm", name: "Условие показа объявления" },
  { "attribute-name": "ym:ev:firstExpenseContent", name: "Контент объявления" },
]